### PR TITLE
Remove typo from package.json

### PR DESCRIPTION
**Pull request by leviathan88**
While testing out the project, I noticed in _master_ branch, there is (I assume) a typo, _protocol_ package is referenced as _protocol2_ which breaks the npm install

### CODE REVIEW

**Comment by SilentCicero** [comment]
@leviathan88 thanks for this, so `protocol2` was used in a migration, it wasn't a typo, that's odd it was causing an issue as we didn't see any issue on our CI at the time.

Regardless everything has now upgraded to where we *can* swap the `protocol2` dependancy for `protocol` (as we have now migrated).

I'll take a look at this, should be able to merge if all is well.

**Review by SilentCicero — APPROVED** [review]
I think this looks good, just going to re-run locally before merging.

**Comment by SilentCicero** [comment]
On it!

**Comment by SilentCicero** [comment]
@leviathan88 after local inspection, all the current files in `tests` require `@fuel-js/protocol2`, so that will need to be replaced out for `@fuel-js/protocol` in order for this to work. 

I did a find and replace locally doing the above and all tests properly pass, so if you would like to do that, go ahead. Otherwise, I can make a separate push on my end for this.

Secondly, we I noticed during inspection when swapping out `protocol2` of `protocol` that the tests *can* fail silently which they did when I initially inspected your PR, this can be easily addressed by wrapping `./src/tests` in a try / catch and throwing the error in that context.

This is also worth another PR I can do later today.

**Comment by leviathan88** [comment]
@SilentCicero thanks I will check it out and update the PR

**Comment by SilentCicero** [comment]
@leviathan88 thanks for this, will await your changes.

**Comment by leviathan88** [comment]
@SilentCicero I have removed protocol2 from tests

**Comment by SilentCicero** [comment]
Thanks Elvis, will review!

**Pull request merged**
